language: node_js
node_js:
  - "stable"
install:
  - npm install
before_install:
  - npm install express
  - npm install consign
  - npm install body-parser
  - npm install mocha chai --save-dev
  - npm install supertest --save-dev
after_success:
  - npm run test-with-coverage
